### ISSUE TITLE
gifsicle pre-build test failed

### ISSUE THREAD

**Issue by yangdan8** [anncwb/vite-plugin-imagemin#18]
Output:
Response code 404 (Not Found)
gifsicle pre-build test failed
compiling from source
Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "autoreconf -ivf"

**Comment by anncwb** [comment]
fixed 0.5.1

**Comment by Skellord** [comment]
Still have this issue
`#18 224.9 Output:
#18 224.9 ⚠ spawn /workspace/node_modules/gifsicle/vendor/gifsicle ENOENT
#18 224.9   ⚠ gifsicle pre-build test failed
#18 224.9   ℹ compiling from source
#18 224.9   ✖ Error: Command failed: /bin/sh -c autoreconf -ivf
#18 224.9 /bin/sh: autoreconf: not found
`
